/* ════════════════════════════════════════════════════
   H&H — Menu Data Module
   All prices in Philippine Peso (₱) — EXACT VALUES
   ════════════════════════════════════════════════════ */

export const MENU_CATEGORIES = [
  'Combo Meals',
  'French Fries',
  'Frappe / Iced Coffee',
  'Smoothies',
  'Coolers',
  'Burgers',
  'Pasta',
  'Salad',
  'Packages',
  'Custom Cakes',
];

const CATEGORY_ICONS = {
  'Combo Meals': '🍱',
  'French Fries': '🍟',
  'Drinks': '🥤',
  'Frappe / Iced Coffee': '☕',
  'Smoothies': '🥤',
  'Coolers': '🧊',
  'Burgers': '🍔',
  'Pasta': '🍝',
  'Salad': '🥗',
  'Packages': '📦',
  'Custom Cakes': '🎂',
};

export function getCategoryIcon(category) {
  return CATEGORY_ICONS[category] || '🍽️';
}

/* gradient colours per category for card backgrounds */
const CATEGORY_GRAD = {
  'Combo Meals': '#f97316,#f59e0b',
  'French Fries': '#eab308,#facc15',
  'Drinks': '#06b6d4,#22d3ee',
  'Frappe / Iced Coffee': '#78350f,#a16207',
  'Smoothies': '#d946ef,#a855f7',
  'Coolers': '#0ea5e9,#38bdf8',
  'Burgers': '#dc2626,#f87171',
  'Pasta': '#ea580c,#fb923c',
  'Salad': '#16a34a,#4ade80',
  'Packages': '#7c3aed,#a78bfa',
  'Custom Cakes': '#ec4899,#f472b6',
};

export function getCategoryGrad(category) {
  return CATEGORY_GRAD[category] || '#6366f1,#818cf8';
}

/* ─── MENU ITEMS ─────────────────────────────────── */

export const menuItems = [

  /* ═══════ COMBO MEALS ═══════ */
  {
    id: 'combo_001',
    name: 'H&H Combo 1',
    category: 'Combo Meals',
    description: 'Spaghetti Bolognese + Fries + Coolers (any) + Brownie',
    price: 120,
    image: 'images/Combo1.jpg',
    includes: ['Spaghetti Bolognese', 'Fries', 'Coolers (any)', 'Brownie'],
    upgrades: [
      { label: 'Upgrade to Frappe', price: 40 },
      { label: 'Upgrade to Smoothie', price: 60 },
    ],
    variants: [],
    addons: [],
  },
  {
    id: 'combo_002',
    name: 'H&H Combo 2',
    category: 'Combo Meals',
    description: 'Burger + Fries + Coolers (any) + Brownie',
    price: 120,
    image: 'images/Combo2.jpg',
    includes: ['Burger', 'Fries', 'Coolers (any)', 'Brownie'],
    upgrades: [
      { label: 'Upgrade to Frappe', price: 40 },
      { label: 'Upgrade to Smoothie', price: 60 },
    ],
    variants: [],
    addons: [],
  },
  {
    id: 'combo_003',
    name: 'H&H Combo 3',
    category: 'Combo Meals',
    description: 'Spaghetti + Burger + Fries + Coolers (any) + Brownie',
    price: 170,
    image: 'images/Combo3.jpg',
    includes: ['Spaghetti', 'Burger', 'Fries', 'Coolers (any)', 'Brownie'],
    upgrades: [
      { label: 'Upgrade to Frappe', price: 40 },
      { label: 'Upgrade to Smoothie', price: 60 },
    ],
    variants: [],
    addons: [],
  },

  /* ═══════ FRENCH FRIES ═══════ */
  {
    id: 'fries_001',
    name: 'Plain Fries',
    category: 'French Fries',
    description: 'Classic golden french fries',
    price: 50,
    image: 'images/Fries.jpg',
    variants: [
      { label: 'Full', price: 100 },
      { label: 'Half', price: 50 },
    ],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Extra Cheese Sauce', price: 20 }, { label: 'Bacon Bits', price: 20 }],
  },
  {
    id: 'fries_002',
    name: 'Fries with Bacon & Cheese',
    category: 'French Fries',
    description: 'Loaded fries with crispy bacon and melted cheese',
    price: 70,
    image: 'images/French Fries.jpg',
    variants: [
      { label: 'Full', price: 120 },
      { label: 'Half', price: 70 },
    ],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Extra Cheese Sauce', price: 20 }, { label: 'Bacon Bits', price: 20 }],
  },

  /* ═══════ FRAPPE / ICED COFFEE ═══════ */
  {
    id: 'frappe_001',
    name: 'Chocolate Frappe',
    category: 'Frappe / Iced Coffee',
    description: 'Rich chocolate iced blend',
    price: 85,
    image: 'images/Chocolate.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Jelly', price: 15 }],
  },
  {
    id: 'frappe_002',
    name: 'Caramel Frappe',
    category: 'Frappe / Iced Coffee',
    description: 'Sweet caramel iced blend',
    price: 85,
    image: 'images/Caramel.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Jelly', price: 15 }],
  },
  {
    id: 'frappe_003',
    name: 'Mocha Frappe',
    category: 'Frappe / Iced Coffee',
    description: 'Coffee-chocolate iced blend',
    price: 85,
    image: 'images/Mocha.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Jelly', price: 15 }],
  },
  {
    id: 'frappe_004',
    name: 'White Chocolate Frappe',
    category: 'Frappe / Iced Coffee',
    description: 'Creamy white chocolate iced blend',
    price: 85,
    image: 'images/White Chocolate.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Jelly', price: 15 }],
  },
  {
    id: 'frappe_005',
    name: 'Cookies & Cream Frappe',
    category: 'Frappe / Iced Coffee',
    description: 'Cookies and cream iced blend',
    price: 85,
    image: 'images/Cookies and Cream.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Jelly', price: 15 }],
  },
  {
    id: 'frappe_006',
    name: 'Caramel Macchiato',
    category: 'Frappe / Iced Coffee',
    description: 'Espresso with caramel and steamed milk',
    price: 85,
    image: 'images/Caramel Macchiato.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Jelly', price: 15 }],
  },
  {
    id: 'frappe_007',
    name: 'Latte / Americano',
    category: 'Frappe / Iced Coffee',
    description: 'Smooth espresso with milk',
    price: 85,
    image: 'images/LatteAmericano.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Jelly', price: 15 }],
  },


  /* ═══════ SMOOTHIES ═══════ */
  {
    id: 'smoothie_001',
    name: 'Blue Velvet',
    category: 'Smoothies',
    description: 'Refreshing blue velvet smoothie',
    price: 100,
    image: 'images/Blue Velvet.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Jelly', price: 15 }, { label: 'Nata de Coco', price: 15 }],
  },
  {
    id: 'smoothie_002',
    name: 'Strawberry Blonde',
    category: 'Smoothies',
    description: 'Sweet strawberry blend',
    price: 100,
    image: 'images/Strawberry Blonde.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Jelly', price: 15 }, { label: 'Nata de Coco', price: 15 }],
  },
  {
    id: 'smoothie_003',
    name: 'Breakfast Smoothie',
    category: 'Smoothies',
    description: 'Energizing breakfast blend',
    price: 100,
    image: 'images/Mocha Smoothie.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Jelly', price: 15 }, { label: 'Nata de Coco', price: 15 }],
  },
  {
    id: 'smoothie_004',
    name: 'Mango Shake',
    category: 'Smoothies',
    description: 'Fresh mango shake',
    price: 75,
    image: 'images/Mango Shake.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Jelly', price: 15 }, { label: 'Nata de Coco', price: 15 }],
  },
  {
    id: 'smoothie_005',
    name: 'Matcha Tea',
    category: 'Smoothies',
    description: 'Japanese matcha green tea blend',
    price: 75,
    image: 'images/Matcha.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Jelly', price: 15 }, { label: 'Nata de Coco', price: 15 }],
  },

  /* ═══════ COOLERS ═══════ */
  {
    id: 'cooler_001',
    name: 'Cucumber Cooler',
    category: 'Coolers',
    description: 'Refreshing cucumber drink',
    price: 50,
    image: 'images/Cucumber.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Jelly', price: 15 }, { label: 'Nata de Coco', price: 15 }],
  },
  {
    id: 'cooler_002',
    name: 'Iced Lemon Tea',
    category: 'Coolers',
    description: 'Classic iced lemon tea',
    price: 50,
    image: 'images/ICED LEMON TEA.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Jelly', price: 15 }, { label: 'Nata de Coco', price: 15 }],
  },
  {
    id: 'cooler_003',
    name: 'Mogu Style',
    category: 'Coolers',
    description: 'Mogu-style refreshment with nata de coco',
    price: 50,
    image: 'images/Mogu Style.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Jelly', price: 15 }, { label: 'Nata de Coco', price: 15 }],
  },

  /* ═══════ BURGERS ═══════ */
  {
    id: 'burger_001',
    name: 'H&H Signature Burger',
    category: 'Burgers',
    description: 'Our signature house burger',
    price: 100,
    image: 'images/Signature Burger.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Extra Cheese', price: 15 }, { label: 'Extra Patty', price: 30 }, { label: 'Bacon', price: 25 }, { label: 'Egg', price: 15 }],
  },
  {
    id: 'burger_002',
    name: 'H&H Whopper',
    category: 'Burgers',
    description: 'Extra-large whopper-style burger',
    price: 100,
    image: 'images/BBQ Chicken Burger.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Extra Cheese', price: 15 }, { label: 'Extra Patty', price: 30 }, { label: 'Bacon', price: 25 }, { label: 'Egg', price: 15 }],
  },
  {
    id: 'burger_003',
    name: 'BBQ Chicken Burger',
    category: 'Burgers',
    description: 'Grilled chicken with BBQ sauce',
    price: 70,
    image: 'images/Chicken Burger.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Extra Cheese', price: 15 }, { label: 'Extra Patty', price: 30 }, { label: 'Bacon', price: 25 }, { label: 'Egg', price: 15 }],
  },
  {
    id: 'burger_004',
    name: 'Chicken Fillet Burger',
    category: 'Burgers',
    description: 'Crispy chicken fillet sandwich',
    price: 60,
    image: 'images/Chicken Fillet Burger.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Extra Cheese', price: 15 }, { label: 'Extra Patty', price: 30 }, { label: 'Bacon', price: 25 }, { label: 'Egg', price: 15 }],
  },
  {
    id: 'burger_005',
    name: 'Cheesy Beef Burger',
    category: 'Burgers',
    description: 'Juicy beef patty with melted cheese',
    price: 65,
    image: 'images/Cheesy Beef Burger.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Extra Cheese', price: 15 }, { label: 'Extra Patty', price: 30 }, { label: 'Bacon', price: 25 }, { label: 'Egg', price: 15 }],
  },
  {
    id: 'burger_006',
    name: 'Bacon & Egg Burger',
    category: 'Burgers',
    description: 'Crispy bacon and sunny egg burger',
    price: 75,
    image: 'images/Bacon and Egg Burger.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Extra Cheese', price: 15 }, { label: 'Extra Patty', price: 30 }, { label: 'Bacon', price: 25 }, { label: 'Egg', price: 15 }],
  },
  {
    id: 'burger_007',
    name: 'Egg & Cheese Burger',
    category: 'Burgers',
    description: 'Classic egg and cheese sandwich',
    price: 50,
    image: 'images/Egg and Cheese Burger.png',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Extra Cheese', price: 15 }, { label: 'Extra Patty', price: 30 }, { label: 'Bacon', price: 25 }, { label: 'Egg', price: 15 }],
  },

  /* ═══════ PASTA ═══════ */
  {
    id: 'pasta_001',
    name: 'Carbonara',
    category: 'Pasta',
    description: 'Creamy carbonara pasta',
    price: 60,
    image: 'images/Carbonara.jpg',
    variants: [
      { label: 'Full', price: 120 },
      { label: 'Half', price: 60 },
    ],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Toasted Bread', price: 20 }, { label: 'Extra Cheese', price: 15 }],
  },
  {
    id: 'pasta_002',
    name: 'Spaghetti Bolognese',
    category: 'Pasta',
    description: 'Classic bolognese meat sauce pasta',
    price: 60,
    image: 'images/Spaghetti Blognese.jpg',
    variants: [
      { label: 'Full', price: 120 },
      { label: 'Half', price: 60 },
    ],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Toasted Bread', price: 20 }, { label: 'Extra Cheese', price: 15 }],
  },
  {
    id: 'pasta_003',
    name: 'Chicken Pesto',
    category: 'Pasta',
    description: 'Pasta with basil pesto and chicken',
    price: 60,
    image: 'images/Chicken Pesto.jpg',
    variants: [
      { label: 'Full', price: 120 },
      { label: 'Half', price: 60 },
    ],
    includes: [],
    upgrades: [],
    addons: [{ label: 'Toasted Bread', price: 20 }, { label: 'Extra Cheese', price: 15 }],
  },

  /* ═══════ SALAD ═══════ */
  {
    id: 'salad_001',
    name: 'H&H Delight Salad',
    category: 'Salad',
    description: 'House special delight salad',
    price: 80,
    image: 'images/Delight Salad.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [
      { label: 'Toasted Bread', price: 20 },
      { label: 'Chicken Strips', price: 20 },
      { label: 'Boiled Egg', price: 20 },
    ],
  },
  {
    id: 'salad_002',
    name: 'Caesar Salad',
    category: 'Salad',
    description: 'Classic Caesar with parmesan and croutons',
    price: 80,
    image: 'images/Ceasar Salad.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [
      { label: 'Toasted Bread', price: 20 },
      { label: 'Chicken Strips', price: 20 },
      { label: 'Boiled Egg', price: 20 },
    ],
  },
  {
    id: 'salad_003',
    name: 'Zivons Salad',
    category: 'Salad',
    description: 'Fresh Zivons-style garden salad',
    price: 100,
    image: 'images/Zivons Salad.jpg',
    variants: [],
    includes: [],
    upgrades: [],
    addons: [
      { label: 'Toasted Bread', price: 20 },
      { label: 'Chicken Strips', price: 20 },
      { label: 'Boiled Egg', price: 20 },
    ],
  },

  /* ═══════ PACKAGES ═══════ */
  {
    id: 'pkg_001',
    name: 'Package #1',
    category: 'Packages',
    description: '15-20 pax',
    price: 2950,
    image: 'images/Package 1.jpg',
    variants: [],
    includes: [
      'Spaghetti Bolognese',
      'Pancit Guisado',
      'Lumpia Shanghai',
      'Veg. Salad',
      'Rectangular cake (7×11×12)',
    ],
    upgrades: [],
    addons: [],
    paxCount: '15-20 pax',
  },
  {
    id: 'pkg_002',
    name: 'Package #2',
    category: 'Packages',
    description: '15-20 pax',
    price: 2950,
    image: 'images/Package 2.jpg',
    variants: [],
    includes: [
      'Bake Mac',
      'Carbonara',
      'Veg. Salad',
      'Club House Sandwich',
      'Rectangular Cake (7×11×12)',
    ],
    upgrades: [],
    addons: [],
    paxCount: '15-20 pax',
  },
  {
    id: 'pkg_003',
    name: 'Package #3',
    category: 'Packages',
    description: '8-12 pax',
    price: 1750,
    image: 'images/Package 1.jpg',
    variants: [],
    includes: [
      'Plain Rice',
      'Fried Chicken (BDO)',
      'Butter Shrimp',
      'Veg. Salad',
      'Fruit Salad',
    ],
    upgrades: [],
    addons: [],
    paxCount: '8-12 pax',
  },
  {
    id: 'pkg_004',
    name: 'Package #4 – Breakfast',
    category: 'Packages',
    description: '8-10 pax',
    price: 1110,
    image: 'images/Package 4.jpg',
    variants: [],
    includes: [
      'Pancake',
      'Waffle',
      'Toasted bread',
      'Coffee Americano or Hot Choco',
    ],
    upgrades: [],
    addons: [],
    paxCount: '8-10 pax',
  },
  {
    id: 'pkg_005',
    name: 'Package #5',
    category: 'Packages',
    description: '8-12 pax',
    price: 1400,
    image: 'images/Package 5.jpg',
    variants: [],
    includes: [
      'Chinese fried Rice',
      'Egg',
      'Ham',
      'Lumpia',
      'Veg. Salad',
      'Fruits Cuts (any available)',
    ],
    upgrades: [],
    addons: [],
    paxCount: '8-12 pax',
  },
  {
    id: 'pkg_006',
    name: 'Package #6 – Dessert',
    category: 'Packages',
    description: 'Dessert package',
    price: 2500,
    image: 'images/Package 6.jpg',
    variants: [],
    includes: [
      'Yema cake',
      'Brownies',
      'Cupcake',
      'Macaroons',
      'Rectangular Cake (7×11×12)',
    ],
    upgrades: [],
    addons: [],
    paxCount: 'Dessert',
  },
  {
    id: 'pkg_007',
    name: 'Package #7',
    category: 'Packages',
    description: '4-5 person',
    price: 600,
    image: 'images/Package7.jpg',
    variants: [],
    includes: [
      'Spaghetti',
      'Vegetable Salad',
      '3 pcs Burger (cut into halves)',
      '1 Pack Brownies',
    ],
    upgrades: [],
    addons: [],
    paxCount: '4-5 person',
  },
  {
    id: 'pkg_008',
    name: 'Package #8',
    category: 'Packages',
    description: '10-12 person',
    price: 1250,
    image: 'images/Package 8.jpg',
    variants: [],
    includes: [
      'Spaghetti',
      'Vegetable Salad',
      '3 pcs Burger (cut into halves)',
      'Yema Loaf',
    ],
    upgrades: [],
    addons: [],
    paxCount: '10-12 person',
  },

  /* ═══════ CUSTOM CAKES ═══════ */
  {
    id: 'custom_cake_001',
    name: 'Custom Cake',
    category: 'Custom Cakes',
    description: 'Design your own cake with custom flavors, shapes, sizes, and toppings',
    price: 350,
    image: 'images/Package 6.jpg',
    isCustomCake: true,
    variants: [],
    includes: [],
    upgrades: [],
    addons: [],
    customOptions: {
      flavors: ['Chocolate', 'Vanilla', 'Red Velvet', 'Ube', 'Mango', 'Mocha', 'Strawberry', 'Yema'],
      shapes: [
        { label: 'Round', extraPrice: 0 },
        { label: 'Square', extraPrice: 50 },
        { label: 'Heart', extraPrice: 75 },
        { label: 'Rectangular', extraPrice: 50 },
      ],
      sizes: [
        { label: '6"', extraPrice: 0 },
        { label: '8"', extraPrice: 150 },
        { label: '10"', extraPrice: 300 },
        { label: '12"', extraPrice: 500 },
      ],
      toppings: [
        { label: 'Sprinkles', price: 25 },
        { label: 'Fresh Berries', price: 25 },
        { label: 'Chocolate Shavings', price: 25 },
        { label: 'Edible Flowers', price: 25 },
        { label: 'Fondant Decor', price: 25 },
        { label: 'Gold Leaf', price: 25 },
        { label: 'Macarons', price: 25 },
        { label: 'Candy Bits', price: 25 },
      ],
    },
  },
];

/**
 * Get all menu items
 */
export function getMenuItems() {
  return menuItems;
}

/**
 * Get a single menu item by ID
 */
export function getMenuItem(id) {
  return menuItems.find(item => item.id === id) || null;
}

/**
 * Get items filtered by category
 */
export function getItemsByCategory(category) {
  return menuItems.filter(item => item.category === category);
}
